### ISSUE TITLE
x1.1.delta: Conceptual Mappings - Section VI: Organisation IDs

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#114] opened 2022-08-22 13:24 UTC
Why do for the RDF file for  the Reviewer, Mediator and the ReviewProcedureInformationProvider all have an ID which is the same as the name of the organisation? 

See 2705-2021 which has no ID for these elements in the xml;

**Comment by costezki** [comment] 2022-09-07 13:27
This is a duplicate of #128

**Closed** 2022-10-29 09:16 UTC
Labels: duplicate, Fixed
