### ISSUE TITLE
CPV and supplementary CPV

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#119] opened 2022-08-30 09:18 UTC
In sections II.1.2. and II.1.2.1 both the Main CPV code and the Supplemenatary CPV code should use the predicate hasMainClassification.

In Sections II.2.2.1 and II.2.2.2 both Main CPV  code and the Supplementary CPV code should use the predicate hasAdditionalClassification

Also to be noted is the Supplemenary CPV is missing from the ontology probably due to the fact that it is not used in eForms

II.2.2.1 only one code shown see 348503-2021 also 337360-2021

**Comment by costezki** [comment] 2022-09-07 12:40
This is different from what we have discussed. 
The proposal in the issue is to map the main CPV on the Procedure level, and what comes at the Lot level to be marked as additional CPV. Is that right? We need to further discuss this.

**Comment by costezki** [comment] 2022-09-07 12:59
![image](https://user-images.githubusercontent.com/13567133/188884091-50635acd-a1e8-4cdc-b3e5-3b8433ef7bfe.png)

![image](https://user-images.githubusercontent.com/13567133/188883999-160740a2-524d-498e-b84c-fe0dfe55c578.png)

**Comment by costezki** [comment] 2022-09-08 15:02
CPV_MAIN and CPV_ADDITIONAL shall be treated in the same manner (i.e. the same mapping rule), see `cpv_set`. 

CPV_MAIN/CPV_CODE -> hasMainClassification (common procurement vocabulary values)
CPV_ADDITIONAL/CPV_CODE -> hasAdditionalClassification (common procurement vocabulary values)

The ontology v3.0.0 does not provide relations to the CPV_SUPPLEMENTARY code lists. 

*Note:*
MAIN_CPV is at the Procedure level, and CPV_ADDITIONAL is at the Lot level. CPV_ADDITIONAL is NOT the same as supplementary; it can still have main and supplementary codes.

![image](https://user-images.githubusercontent.com/13567133/189156051-3a1177b3-909b-4513-8f46-b8337ace5fb3.png)

**Comment by andreea-pasare** [comment] 2022-09-13 08:34
The next ePO version will provide the following:

CPV_MAIN/CPV_CODE -> hasMainClassification (at-voc:cpv)
CPV_ADDITIONAL/CPV_CODE -> hasAdditionalClassification (at-voc:cpv)

CPV_MAIN/CPV_SUPPLEMENTARY -> hasMainSupplementaryClassification (at-voc:cpvsuppl)
CPV_ADDITIONAL/CPV_SUPPLEMENTARY -> hasAdditionalSupplementaryClassification (at-voc:cpvsuppl)

![image](https://user-images.githubusercontent.com/88081600/189852378-e0a4937f-e3e8-4f2d-bf1b-89debcbfd5a8.png)

**Comment by muricna** [comment] 2022-09-13 08:41
In my opinion this is not necessary.  The code lists are just recommendation so we can map to cpvsuppl directly from has AdditionalClassification and has MainClassification

**Comment by muricna** [comment] 2022-10-27 06:58
This solution does not completely fit for the Supplementary code as it should be associated with a particular CPV code see 366836-2021

**Comment by costezki** [comment] 2022-11-09 09:29
The `at-voc:cvbsuppl` has been added back into the EPO model. 

![image](https://user-images.githubusercontent.com/13567133/200792636-c089990a-651d-45a0-b897-6c7b1af5021d.png)

**Comment by muricna** [comment] 2023-01-18 12:30
The result in the rdf provides no association between the CPV and the Supplementary CPV.  Due to the complexity here the mapping of the Supplementary CPV should be removed and an appropriate remark made in the conceptual mapping which should then be reflected in the rdf.

**Comment by andreea-pasare** [comment] 2023-01-24 13:19
The remark in the rdf output should be provided as an rdfs:comment statement.

**Comment by csnyulas** [comment] 2023-01-25 21:48
This is a related issue (just to link them): #205

**Comment by costezki** [comment] 2023-02-01 09:35
The supplementary needs to be associated with the “normal” CPV. This association is not supported in the EPO, and it is not foreseen to be supported in the future.  Therefore, the mapping to supplementary CPV is dropped forever. In the CM we just make a remark that it is NOT mapped. Nothing is done in the Output.

**Comment by csnyulas** [comment] 2023-02-17 11:52
Closing this as it has been addressed in the technical mapping where we have commented out all mappings related to supplementary CPV codes (see referenced commits), and also in the conceptual mapping (starting with CM v.6.6.7), where we have removed the mappings of supplementary CPV codes, and provided appropriate explanations in the "Mapping Remarks" sheet.

**Closed by csnyulas** 2023-02-17 11:52 UTC
Labels: type: bug

**Comment by muricna** [comment] 2023-05-05 14:34
The mapping needs to be removed from the conceptual model as it is not used.
