### ISSUE TITLE
x1.1.delta: Conceptual Mappings: Section II.2.4: Description of the Procurement - missing

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#107] opened 2022-08-22 07:52 UTC
This concerns the description of the lot.  
In notice 2705-2021 there is only one lot as the ontology defines all procedures should have at least one lot however this information is missing.

**Comment by costezki** [comment] 2022-09-07 14:13
This is a duplicate of #120 #117 .

**Closed** 2022-10-28 09:11 UTC
Labels: type: bug, duplicate, Fixed
