### ISSUE TITLE
tx1-2: remove reference to previous notice in ProcurementProcessInformation

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#244] opened 2022-11-23 10:46 UTC
![image](https://user-images.githubusercontent.com/13567133/203527108-d0975641-e9a9-4d47-a945-303de2056d21.png)

**Comment by fokoug** [comment] 2022-11-23 20:34
![Screenshot 2022-11-23 at 21 34 03](https://user-images.githubusercontent.com/24571803/203641340-5843a50e-3fd2-400e-8bb7-cc0a9dae6f8c.png)

Comment epo:concernsPreviousNotice

**Comment by csnyulas** [comment] 2022-11-24 08:20
Addressed in commit https://github.com/OP-TED/ted-rdf-mapping/commit/3c876b2f249d4cd1b8acceb28485b124b4ac2632

**Comment by csnyulas** [comment] 2022-11-30 11:09
Conceptual mapping was also fixed by removing the line about the reference to the previous notice from the `ProcurementProcessInformation`, and not creating the ProcurementProcessInformation (and linking it to the current procedure), unless there is a `TERMINATION_DPS` or `TERMINATION_PIN XML` element (i.e. the presence of the `NOTICE_NUMBER_OJ` element is not enough reason to create the `ProcurementProcessInformation` instance).

used to be:
![image](https://user-images.githubusercontent.com/2441046/204780792-e2fd92c6-b32a-4dcc-ad9b-f5425caa0a90.png)

and now is:
![image](https://user-images.githubusercontent.com/2441046/204779828-4bb7015d-3f54-4b29-967c-077d855ad6d5.png)

**Comment by csnyulas** [comment] 2022-12-01 08:19
Closing this as a fix was provided (with reference to this issue, see above) and the generated output is as expected (see recent references).

Note for @fokoug : The analysis of the validation reports needs to be updated as there are new "fake" invalids that were caused by the fact that we are not creating `epo:ProcurementProcessInformation` instance that do not contain any attached information to it (i.e. the presence of the `NOTICE_NUMBER_OJ` element is not reason enough to create a ProcurementProcessInformation instance. Only when there is a `TERMINATION_DPS` or `TERMINATION_PIN` element will we create a ProcurementProcessInformation instance. This is expressed as an XPATH condition in the CM, however this cannot be handled by the validation report generator)

**Closed by csnyulas** 2022-12-01 08:19 UTC
Labels: type: bug, Fixed
