### ISSUE TITLE
SaxonApiException

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping#434] opened 2024-06-24 08:53 UTC
@Dragos0000 suggested to report in the corresponding mapping repository.

We are trying to transform some notices for a given day using https://github.com/OP-TED/ted-rdf-conversion-pipeline . 

Some of them are failing with this the following error:

![image](https://github.com/OP-TED/ted-rdf-mapping/assets/361916/65393809-7ecc-4598-a2c9-ac9e78ada1ae)

```
net.sf.saxon.s9api.SaxonApiException: A sequence of more than one item is not allowed as the first argument of fn:path() (<cac:ProcurementProjectLot>, <cac:ProcurementProjectLot>) at net.sf.saxon.s9api.XPathSelector.evaluate(XPathSelector.java:233) at net.sf.saxon.s9api.XPathCompiler.evaluate(XPathCompiler.java:610) at be.ugent.rml.records.XMLRecord.get(XMLRecord.java:37) at be.ugent.rml.extractor.ReferenceExtractor.extract(ReferenceExtractor.java:31) at be.ugent.rml.extractor.ReferenceExtractor.execute(ReferenceExtractor.java:41) at be.ugent.rml.functions.StaticMultipleRecordsFunctionExecutor.execute(StaticMultipleRecordsFunctionExecutor.java:30) at be.ugent.rml.Executor.getIRIsWithTrueCondition(Executor.java:309) at be.ugent.rml.Executor.getIRIsWithConditions(Executor.java:273) at be.ugent.rml.Executor.generatePredicateObjectGraphs(Executor.java:227) at be.ugent.rml.Executor.executeWithFunction(Executor.java:165) at be.ugent.rml.Executor.execute(Executor.java:123) at be.ugent.rml.cli.Main.run(Main.java:412) at be.ugent.rml.cli.Main.main(Main.java:46) Caused by: net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the first argument of fn:path() (<cac:ProcurementProjectLot>, <cac:ProcurementProjectLot>) at net.sf.saxon.expr.Expression.typeError(Expression.java:1477) at net.sf.saxon.expr.CardinalityChecker.evaluateItem(CardinalityChecker.java:296) at net.sf.saxon.expr.parser.Evaluator$OptionalItem.evaluate(Evaluator.java:201) at net.sf.saxon.expr.SystemFunctionCall.evaluateArguments(SystemFunctionCall.java:469) at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:560) at net.sf.saxon.sxpath.XPathExpression.iterate(XPathExpression.java:176) at net.sf.saxon.s9api.XPathSelector.evaluate(XPathSelector.java:229) ... 12 more net.sf.saxon.s9api.SaxonApiException: A sequence of more than one item is not allowed as the first argument of fn:path() (<cac:ProcurementProjectLot>, <cac:ProcurementProjectLot>) at net.sf.saxon.s9api.XPathSelector.evaluate(XPathSelector.java:233) at net.sf.saxon.s9api.XPathCompiler.evaluate(XPathCompiler.java:610) at be.ugent.rml.records.XMLRecord.get(XMLRecord.java:37) at be.ugent.rml.extractor.ReferenceExtractor.extract(ReferenceExtractor.java:31) at be.ugent.rml.extractor.ReferenceExtractor.execute(ReferenceExtractor.java:41) at be.ugent.rml.functions.StaticMultipleRecordsFunctionExecutor.execute(StaticMultipleRecordsFunctionExecutor.java:30) at be.ugent.rml.Executor.getIRIsWithTrueCondition(Executor.java:309) at be.ugent.rml.Executor.getIRIsWithConditions(Executor.java:273) at be.ugent.rml.Executor.generatePredicateObjectGraphs(Executor.java:227) at be.ugent.rml.Executor.executeWithFunction(Executor.java:165) at be.ugent.rml.Executor.execute(Executor.java:123) at be.ugent.rml.cli.Main.run(Main.java:412) at be.ugent.rml.cli.Main.main(Main.java:46) Caused by: net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the first argument of fn:path() (<cac:ProcurementProjectLot>, <cac:ProcurementProjectLot>) at net.sf.saxon.expr.Expression.typeError(Expression.java:1477) at net.sf.saxon.expr.CardinalityChecker.evaluateItem(CardinalityChecker.java:296) at net.sf.saxon.expr.parser.Evaluator$OptionalItem.evaluate(Evaluator.java:201) at net.sf.saxon.expr.SystemFunctionCall.evaluateArguments(SystemFunctionCall.java:469) at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:560) at net.sf.saxon.sxpath.XPathExpression.iterate(XPathExpression.java:176) at net.sf.saxon.s9api.XPathSelector.evaluate(XPathSelector.java:229) ... 12 more net.sf.saxon.s9api.SaxonApiException: A sequence of more than one item is not allowed as the first argument of fn:path() (<cac:ProcurementProjectLot>, <cac:ProcurementProjectLot>) at net.sf.saxon.s9api.XPathSelector.evaluate(XPathSelector.java:233) at net.sf.saxon.s9api.XPathCompiler.evaluate(XPathCompiler.java:610) at be.ugent.rml.records.XMLRecord.get(XMLRecord.java:37) at be.ugent.rml.extractor.ReferenceExtractor.extract(ReferenceExtractor.java:31) at be.ugent.rml.extractor.ReferenceExtractor.execute(ReferenceExtractor.java:41) at be.ugent.rml.functions.StaticMultipleRecordsFunctionExecutor.execute(StaticMultipleRecordsFunctionExecutor.java:30) at be.ugent.rml.Executor.getIRIsWithTrueCondition(Executor.java:309) at be.ugent.rml.Executor.getIRIsWithConditions(Executor.java:273) at be.ugent.rml.Executor.generatePredicateObjectGraphs(Executor.java:227) at be.ugent.rml.Executor.executeWithFunction(Executor.java:165) at be.ugent.rml.Executor.execute(Executor.java:123) at be.ugent.rml.cli.Main.run(Main.java:412) at be.ugent.rml.cli.Main.main(Main.java:46) Caused by: net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the first argument of fn:path() (<cac:ProcurementProjectLot>, <cac:ProcurementProjectLot>) at net.sf.saxon.expr.Expression.typeError(Expression.java:1477) at net.sf.saxon.expr.CardinalityChecker.evaluateItem(CardinalityChecker.java:296) at net.sf.saxon.expr.parser.Evaluator$OptionalItem.evaluate(Evaluator.java:201) at net.sf.saxon.expr.SystemFunctionCall.evaluateArguments(SystemFunctionCall.java:469) at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:560) at net.sf.saxon.sxpath.XPathExpression.iterate(XPathExpression.java:176) at net.sf.saxon.s9api.XPathSelector.evaluate(XPathSelector.java:229) ... 12 more net.sf.saxon.s9api.SaxonApiException: A sequence of more than one item is not allowed as the first argument of fn:path() (<cac:ProcurementProjectLot>, <cac:ProcurementProjectLot>) at net.sf.saxon.s9api.XPathSelector.evaluate(XPathSelector.java:233) at net.sf.saxon.s9api.XPathCompiler.evaluate(XPathCompiler.java:610) at be.ugent.rml.records.XMLRecord.get(XMLRecord.java:37) at be.ugent.rml.extractor.ReferenceExtractor.extract(ReferenceExtractor.java:31) at be.ugent.rml.extractor.ReferenceExtractor.execute(ReferenceExtractor.java:41) at be.ugent.rml.functions.StaticMultipleRecordsFunctionExecutor.execute(StaticMultipleRecordsFunctionExecutor.java:30) at be.ugent.rml.Executor.getIRIsWithTrueCondition(Executor.java:309) at be.ugent.rml.Executor.getIRIsWithConditions(Executor.java:273) at be.ugent.rml.Executor.generatePredicateObjectGraphs(Executor.java:227) at be.ugent.rml.Executor.executeWithFunction(Executor.java:165) at be.ugent.rml.Executor.execute(Executor.java:123) at be.ugent.rml.cli.Main.run(Main.java:412) at be.ugent.rml.cli.Main.main(Main.java:46) Caused by: net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the first argument of fn:path() (<cac:ProcurementProjectLot>, <cac:ProcurementProjectLot>) at net.sf.saxon.expr.Expression.typeError(Expression.java:1477) at net.sf.saxon.expr.CardinalityChecker.evaluateItem(CardinalityChecker.java:296) at net.sf.saxon.expr.parser.Evaluator$OptionalItem.evaluate(Evaluator.java:201) at net.sf.saxon.expr.SystemFunctionCall.evaluateArguments(SystemFunctionCall.java:469) at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:560) at net.sf.saxon.sxpath.XPathExpression.iterate(XPathExpression.java:176) at net.sf.saxon.s9api.XPathSelector.evaluate(XPathSelector.java:229) ... 12 more 
```

**Comment by schivmeister** [comment] 2024-06-28 08:49
Thanks for reporting. Unfortunately, we are unable to reproduce this issue on our end, as the transformation works with the following setup:

- **Notice:** [129713-2024](https://ted.europa.eu/en/notice/-/detail/129713-2024)
- **RMLMapper:** [6.2.2](https://github.com/RMLio/rmlmapper-java/releases/tag/v6.2.2)
- **Java:** 11, 17

@cristianvasquez Note that this appears to be an [eForms](https://github.com/OP-TED/ted-rdf-mapping-eforms) notice and specifically a pipeline issue, so this ticket should be moved to the [appropriate project](https://github.com/OP-TED/ted-rdf-conversion-pipeline).

@Dragos0000 Please ensure the pipeline environment conforms to the above setup.

Note that RMLMapper v6.2.2 comes [bundled with Saxon-HE v11.4](https://github.com/RMLio/rmlmapper-java/blob/v6.2.2/pom.xml):

```
        <!-- Saxon Home Edition XML, XPath and XQuery parser API -->
        <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>11.4</version>
        </dependency>
```

**Comment by costezki** [comment] 2024-07-01 07:36
Atfer coordinating with colleagues, it appears that this issue is due to misuse of the pipeline. The operators have loaded incomplete mapping suite which were explicitly marked as `alpha` tags, which are not supposed to be used.

This issue is related to https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/28

**Closed by costezki** 2024-07-01 07:36 UTC

**Comment by cristianvasquez** [comment] 2024-07-01 09:32
Related issue: https://github.com/OP-TED/ted-rdf-mapping-eforms/issues/27
